### ISSUE TITLE
Version 1.43 of the specification is out.

### ISSUE THREAD

**Issue by Yawning** [magical/deoxys#1]
The algorithm designers were kind enough to inform me that the specification has been updated (due to the implementations of this primitive that I maintain for $dayjob), and I'm passing on the favor.

The updated test vectors and spec are available at the page maintained by the algorithm designers (https://sites.google.com/view/deoxyscipher), but in brief, the description of the byte permutation `h` has been clarified.

Most (if not all) implementations based on the prior version of the spec implement the inverse of `h`.

**Comment by magical** [comment]
Thanks, i'll take a look

**Comment by Yawning** [comment]
If it saves you some time, this is my update commit that matches the official test vectors.

https://github.com/oasislabs/deoxysii/commit/3ac8fcd4f1a56568f6687d7fe635f216d351e13a

**Comment by magical** [comment]
Fixed, thanks. Ironically i had gotten the permutation right the first time around, but changed it to match the reference implementation (https://github.com/magical/deoxys/commit/2061493a76d1ceefa954999fdde1fa389a0cb801).
